Vagrant.configure("2") do |config|
  (1..1).each do |i|
    config.vm.define "snmpd-ubuntu-0#{i}" do |node|
      node.vm.box = "bento/ubuntu-24.04"
      node.vm.hostname = "snmpd-ubuntu-0#{i}"
      node.vm.network "public_network", type: "dhcp"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
        vb.name = "snmpd-ubuntu-0#{i}"
      end
    end
  end
end
